name: CLA-bot

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened,closed,sychronized]

jobs:
  CLA-assistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Checker"
        if: (github.event.comment.body == 'recheckcla' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request'
        uses: cla-assistant/github-action@v1.3.0-alpha
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path-to-signatures: 'signatures/version1/cla.json'
          path-To-cladocument: 'https://github.com/ActiveState/cli/blob/master/cla.md'
          # branch should not be protected
          branch: 'clas'
          whitelist: ""
          empty-commit-flag: true
          blockchain-storage-flag: false
